### ISSUE TITLE
innerHTML vs text/value

### ISSUE THREAD

**Issue by ogiermaitre** [brianvoe/slim-select#25]
Hi,

Thanks for this work. It’s a beautiful piece of UI.

From what I get yet, there is no way to show different texts in the ss-multi-selected and the ss-list. 
To be clearer, I use innerHTML to display 2 spans in the ss-list (to mimic label in dataList), one justify left, one right. When I select an item, it is shown as a concatenation of the content of the spans. Is there a way to use the .text property of the data instead of the innerHTML, for the ss-multi-selected > ss-value part, as it is clearly a text only display ?

Thanks again for your work,
Tell me if this is not clear.

Ogier

**Comment by brianvoe** [comment]
Hey Ogier,

Thanks for the words of encouragement. Just to help me visualize what you are describing could you add a couple of screenshots?

Thanks.

P.S. If you like the package would it be ok if you starred it? It really helps me get the word out when someone decides to choose a select dropdown.

**Comment by ogiermaitre** [comment]
Thanks for your response. 

I would like to have categories that look like label in datalist. So currently my design is like that :
![image](https://user-images.githubusercontent.com/24251307/35399158-ec9d6eaa-01f3-11e8-885d-daa918f1e2be.png)

So the object passed to setData are like that :
``` 
{    
    text: o.key,
    innerHTML: `<div style='width:100%' ><span>${o.key}</span><span class='cat'>${cat}</span></span></div>`,
}
```

But when I select an entry, it seems the text shown, is a .text() of my innerHTML.
![image](https://user-images.githubusercontent.com/24251307/35399278-2f496a92-01f4-11e8-88db-c5d2881c9e7b.png)

It seems to me, that the text representation used for the selected entry should come from .text property instead of .innerHTML.text().
Am I correct in my interpretation ?

**Comment by brianvoe** [comment]
Ok i see what your saying. Let me setup an example in the docs and play around with it. Want to make sure my changes reflect well in a innerHtml multi select option.

**Comment by brianvoe** [comment]
Ok this is fixed. I added an option for if you want to show the text value for a selected option you can by passing valuesUseText: boolean. Otherwise default will use innerhtml. I updated the docs to reflect this if you needed to see an example. v1.8.1

Thanks for catching this!

**Comment by cyzanfar** [comment]
`valuesUseText: true` still displays innerhtml content when selected

**Comment by bradojev** [comment]
I can confirm that @cyzanfar is right. Still getting stripped innerHTML instead of text whatever I write in valuesUseText option.
